services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-todo_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    container_name: backend-nestjs
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-todo_db}
      DB_SYNCHRONIZE: "true"
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-main:
    build:
      context: ./frontend-main-angular
      dockerfile: Dockerfile
    container_name: frontend-main-angular
    restart: unless-stopped

  frontend-me:
    build:
      context: ./frontend-main-svelte-context
      dockerfile: Dockerfile
    container_name: frontend-main-svelte-context
    restart: unless-stopped

  frontend-blog:
    build:
      context: ./frontend-blog-vue
      dockerfile: Dockerfile
    container_name: frontend-blog-vue
    restart: unless-stopped

  frontend-cv:
    build:
      context: ./frontend-cv-react
      dockerfile: Dockerfile
    container_name: frontend-cv-react
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./localhost-Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend-main
      - frontend-blog
      - frontend-cv

volumes:
  postgres_data:
  caddy_data:
  caddy_config:



# docker compose -f localhost-build.yml -p hoidanit-multiple-webs up -d